---
title: "Using plantecowrap"
author: "Joseph R. Stinziano"
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
 %\VignetteIndexEntry{Using_plantecophystools}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
---
Load Packages
```{r}
library(plantecowrap)
library(ggplot2)
library(tidyr)
```

Create Example Dataset
```{r}
Tleaf <- seq(from = 10, to = 35, by = 5)
Tleaf <- sort(rep(Tleaf, 15))

Vcmax_start <- 90 * modarrhenius(Ea = 35, Hd = 220, dS = 0.3, Tleaf = Tleaf)
Jmax_start <- 140 * modarrhenius(Ea = 80, Hd = 220, dS = 0.6, Tleaf = Tleaf)
R_start <- 1.5 * arrhenius(Ea = 20, Tleaf = Tleaf)
GammaStar_start <- 42.75 * arrhenius(Ea = 37.83, Tleaf = Tleaf)
Km_start <- 718.40 * arrhenius(Ea = 65.50828, Tleaf = Tleaf)
Ci <- rep(c(75, 100, 150, 200, 250,
        300, 350, 400, 600, 800,
        1000, 1200, 1400, 1600, 1800), 6)
A <- 1:90
Vc <- 1:90
Vj <- 1:90
for(i in seq_along(A)){
Vc[i] <- (Vcmax_start[i] * (Ci[i] - GammaStar_start[i]) / 
               (Ci[i] + Km_start[i]))
Vj[i] <- (Jmax_start[i] * (Ci[i] - GammaStar_start[i]) / 
            (4 * Ci[i] + 8 * GammaStar_start[i]))
if(Vc[i] < 0){
  Vc[i] <- NA
}
if(Vj[i] < 0){
  Vj[i] <- NA
}
A[i] <- min(Vc[i], Vj[i]) - R_start[i]
}

PPFD <- rep(2000, 90)
Press <- rep(100, 90)

data <- data.frame(cbind(A,
                         Ci,
                         Tleaf,
                         Press,
                         PPFD))

data2 <- data.frame(cbind(A,
                         Ci,
                         Tleaf,
                         Press,
                         PPFD))
data2$A <- data2$A * 2

data$Treat <- as.character(Tleaf)
data2$Treat <- as.character(Tleaf)
data2 <- rbind(data, data2)
data2$Block <- c(rep("a", nrow(data)),
                 rep("b", nrow(data)))
data2 <- unite(data2, col = "Grouping", c("Treat", "Block"), sep = "_")
```

Fit ACi Curves then fit temperature responses
```{r}
fits <- fitacis2(data = data,
                 varnames = list(ALEAF = "A",
                                 Tleaf = "Tleaf",
                                 Ci = "Ci",
                                 PPFD = "PPFD",
                                 Rd = "Rd",
                                 Press = "Press"),
                 group1 = "Treat",
                 fitTPU = FALSE,
                 fitmethod = "bilinear",
                 gm25 = 10000,
                 Egm = 0)
#Get ACi outputs
outputs <- acisummary(data, group1 = "Treat", fits = fits)

#Fit temperature response
#Note that this will return NA warnings because it runs through
#1000 sets of starting parameters for Vcmax and Jmax
tresp <- fit_topt_VJ(outputs)

#See parameters
tresp[[2]]

#See plot
tresp[[3]]

```

#Fitting of multiple temperature responses
```{r}
fits2 <- fitacis2(data = data2,
                 varnames = list(ALEAF = "A",
                                 Tleaf = "Tleaf",
                                 Ci = "Ci",
                                 PPFD = "PPFD",
                                 Rd = "Rd",
                                 Press = "Press"),
                 group1 = "Grouping",
                 fitTPU = FALSE,
                 fitmethod = "bilinear",
                 gm25 = 10000,
                 Egm = 0)
#Get ACi outputs
outputs <- acisummary(data2, group1 = "Grouping", fits = fits2)

outputs <- separate(outputs, col = "ID", into = c("Treat", "Block"), sep = "_")

#Note that this will return NA warnings because it runs through
#1000 sets of starting parameters for Vcmax and Jmax
tresps <- fit_topt_VJs(data = outputs,
                       group = "Block")

#Get parameters
pars <- get_t_pars(tresps)

#Get graphs
graphs <- get_t_graphs(tresps)

#Print graphs (uncomment to run)
#print_graphs(graphs)

#View parameters
pars

#View graphs
#Note that the second graph is strange because A was simply multiplied by
#2 for the sample dataset
graphs[[1]]
graphs[[2]]
```